# Generated by Django 4.2.29 on 2026-03-23 05:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='active_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='Days of week the rule may fire: 0=Mon … 6=Sun. Null = all days.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rule',
            name='condition_group_operator',
            field=models.CharField(choices=[('AND', 'AND — all groups must be true'), ('OR', 'OR — any group being true triggers the rule')], default='AND', help_text='How multiple condition groups are combined.', max_length=3),
        ),
        migrations.AlterField(
            model_name='rule',
            name='last_fired_at',
            field=models.DateTimeField(blank=True, help_text='When the rule last transitioned to triggered state.', null=True),
        ),
        migrations.AlterField(
            model_name='ruleaction',
            name='command',
            field=models.JSONField(blank=True, help_text='Command to send: {"name": "command_name", "params": {...}}', null=True),
        ),
        migrations.AlterField(
            model_name='ruleaction',
            name='group_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='NotificationGroup PKs to notify.', size=None),
        ),
        migrations.AlterField(
            model_name='ruleaction',
            name='message_template',
            field=models.TextField(blank=True, help_text='Supports variables: {{device_name}}, {{stream_name}}, {{value}}, {{unit}}, {{triggered_at}}, {{rule_name}}, {{site_name}}.'),
        ),
        migrations.AlterField(
            model_name='ruleaction',
            name='notification_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Delivery channels: in_app, email, sms, push.', size=None),
        ),
        migrations.AlterField(
            model_name='ruleaction',
            name='user_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='TenantUser PKs to notify.', size=None),
        ),
        migrations.AlterField(
            model_name='ruleauditlog',
            name='changed_fields',
            field=models.JSONField(help_text='Dict of {field: {before, after}} for every tracked field.'),
        ),
    ]
