# Generated by Django 4.2.29 on 2026-03-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_devicetype_status_indicator_mappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='status_indicator_mappings',
            field=models.JSONField(blank=True, default=dict, help_text='Per-stream status indicator mappings for the Status Indicator dashboard widget. Keyed by stream key; each value is a list of {value, color, label} entries. Example: {"motor_status": [{"value": "running", "color": "#22C55E", "label": "Running"}]}'),
        ),
    ]
