# Generated by Django 4.2.29 on 2026-04-01 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_add_device_detail_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcedevice',
            name='poll_interval_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Per-device poll interval override (seconds, minimum 30). When null, the provider default_poll_interval_seconds is used.', null=True, validators=[django.core.validators.MinValueValidator(30)]),
        ),
    ]
